### ISSUE TITLE
Undeclared dependencies

### ISSUE THREAD

**Issue by eserte** [glasswalk3r/siebel-monitoring-tools#7]
Tests fail if some modules are not installed (and these probably should be declared as prerequisites, or the tests should be skipped if these are missing):
* Siebel::Srvrmgr::ListParser
* Siebel::Srvrmgr::Daemon::Light

Seen with Siebel-Lbconfig-0.001

**Comment by glasswalk3r** [comment]
Yep, you're write. I totally forgot to declare AutoPreReqs in the dist.ini file.
I'll release a new version in the next few minutes.

**Comment by glasswalk3r** [comment]
Version 0.002 was release and it is already available at http://search.cpan.org/~arfreitas/Siebel-Lbconfig-0.002/. Could you please try and see if the dependencies information is now available? Thanks!

**Comment by glasswalk3r** [comment]
Fixed on 0.002.
