### ISSUE TITLE
t/Siebel-Srvrmgr-Exporter.t fails (depending on PATH)

### ISSUE THREAD

**Issue by eserte** [glasswalk3r/siebel-monitoring-tools#8]
On my smoker systems I see the following failure:
```
PERL_DL_NONLAZY=1 "/bbbike/perl-5.25.6/bin/perl5.25.6" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
Negative repeat count does nothing at /opt/perl-5.25.6/lib/site_perl/5.25.6/Term/YAP.pm line 259, <DATA> line 1.
A failure occurred when trying to submit load preferences: Broken pipe at /opt/perl-5.25.6/lib/site_perl/5.25.6/Siebel/Srvrmgr/Daemon/Heavy.pm line 1140
Negative repeat count does nothing at /opt/perl-5.25.6/lib/site_perl/5.25.6/Term/YAP.pm line 259, <DATA> line 1.
Negative repeat count does nothing at /opt/perl-5.25.6/lib/site_perl/5.25.6/Term/YAP.pm line 259, <DATA> line 1.
        (in cleanup) A failure occurred when trying to submit exit: Broken pipe at /opt/perl-5.25.6/lib/site_perl/5.25.6/Siebel/Srvrmgr/Daemon/Heavy.pm line 1140

#   Failed test 'Failed to execute export_comps.pl: '
#   at t/Siebel-Srvrmgr-Exporter.t line 67.
# Looks like you failed 1 test of 5.
t/Siebel-Srvrmgr-Exporter.t ..
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests
```
It seems that the problem is that the test script tries to execute `export_comps.pl`, which uses `/usr/bin/env perl` in its shebang. This means that on systems, where a custom perl is used which is not in the user's `PATH`, the wrong perl might be picked (i.e. the system perl), causing the test failure.

Using `#!/usr/bin/env perl` also has the side effect that the shebang is not rewritten by ExtUtils::MakeMaker (currently, maybe this will change somewhen in the future). I think it's better to write `#!/usr/bin/perl` or just `#!perl` instead, and for the tests use `blib/script/export_comps.pl`, because there the shebang is already rewritten to the correct perl path.

**Comment by glasswalk3r** [comment]
Thanks for reporting.
I couldn't make out the version of Siebel::Srvrmgr::Exporter this relates too (I'm assuming the latest), but I couldn't find any report (in all those failures that this distro has) that regards to 5.25.6.
That said, it could help me a lot to identify the versions you executed, specially the Term::YAP warnings.
I'm tempted to follow your recommendation but I'm not sure how it would behave in systems that do have a perl in the PATH variable.
I quickly searched about this feature of shebang rewrite ot ExtUtils::MakeMaker, but couldn't find anything about it in the documentations that explains that in more details besides http://search.cpan.org/~bingos/ExtUtils-MakeMaker-7.24/lib/ExtUtils/MM_Unix.pm. If you have any other reference (hopefully with implications) please let me know.

**Comment by eserte** [comment]
The best reference is probably this discussion: https://github.com/Perl-Toolchain-Gang/ExtUtils-MakeMaker/issues/58

**Comment by glasswalk3r** [comment]
Released yesterday the changes proposed, after validating in several different versions of Perl. Let's see how it behaves when tested by other people.

**Comment by glasswalk3r** [comment]
I'm confused... got those two reports from your user:
http://www.cpantesters.org/cpan/report/1b6a602a-b9df-11e6-a66f-717fc671d6e6
http://www.cpantesters.org/cpan/report/42383efa-b9f0-11e6-bd42-c8efac536762
One passed, the other failed... and looks like they came from the same perl version. Could you please take a look what could possible went wrong over there?

**Comment by eserte** [comment]
No, first report is from Andreas' smoker, not mine.

Looking with strace into the test run I see:
```
23187 21:22:43.724236 execve("/usr/local/bin/perl", ["perl", "/opt/perl-5.16.3/bin/srvrmgr-mock.pl", "/e", "foobar", "/g", "foobar", "/u", "foobar", "/l", "ENU", "/s", "foobar"], [/* 40 vars */]) = 0 <0.000285>
...
23187 21:22:43.806439 write(2, "YAML::XS version 0.62 required--this is only version 0.41 at /opt/perl-5.16.3/bin/srvrmgr-mock.pl line 5.\nBEGIN failed--compilation aborted at /opt/perl-5.16.3/bin/srvrmgr-mock.pl line 5.\n", 188) = 188 <0.000027>
```

So the system perl is still used at another place. Probably you have to change this call, i.e. by replacing `perl` with `$^X`, which would reuse the current perl.

**Comment by glasswalk3r** [comment]
Ops... I assumed the reports were aggregate by testers when I got the e-mail report... my apologies.
I'll take a look if there is any way I can control from the tests which perl is actually being invoked.

**Comment by glasswalk3r** [comment]
This should be "fixed" now that I added offline parsing support.
If you would to check before release, please checkout the latest [commit](https://github.com/glasswalk3r/siebel-monitoring-tools/commit/5e4ba9e3398730f4f3bb986993ea7935d0e02bab), although I'm getting the current perl from $Config{perlpath} instead of $^X.
